#!/bin/bash

echo 'Install git-filter-repo'
echo '------------'

wget https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
sudo chmod +x git-filter-repo
mv git-filter-repo /usr/local/bin
